REALITY_DISTANCE_3 = 18.5  # cm
REALITY_PRE_TOOL_CIRCLE_LENGTH = 4.7625  # cm
REALITY_POST_TOOL_CIRCLE_LENGTH = 2.1  # cm
REALITY_TOOL_1_LENGTH = 6.8  # cm

BOARD_WIDTH = 4320  # pixels
BOARD_HEIGHT = 2160  # pixels
COLOUR_WHITE = (255, 255, 255, 255)
SCREEN_WIDTH = 1800
SCREEN_HEIGHT = 900
SCALING = BOARD_WIDTH / SCREEN_WIDTH
DPI = 23.62  # px/cm, as used in Vassal

SCREEN_DISTANCE_3 = REALITY_DISTANCE_3 * DPI
SCREEN_DISTANCE_3_TOP = SCREEN_DISTANCE_3 / SCALING
SCREEN_DISTANCE_3_BOTTOM = SCREEN_HEIGHT - SCREEN_DISTANCE_3_TOP
SCREEN_MIDDLE = SCREEN_WIDTH / 2
SCREEN_PRE_TOOL_CIRCLE_LENGTH = REALITY_PRE_TOOL_CIRCLE_LENGTH * DPI / SCALING
SCREEN_POST_TOOL_CIRCLE_LENGTH = REALITY_POST_TOOL_CIRCLE_LENGTH * DPI / SCALING
SCREEN_TOOL_1_LENGTH = REALITY_TOOL_1_LENGTH * DPI / SCALING
